services:
  mongodbAcademia:
    image: mongo:latest
    container_name: mongodbAcademia
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: mydatabase
    networks:
      - app-network

networks:
  app-network:
    driver: bridge